import { VocabularyWord, LearningSession } from '@/types';

export const MOCK_WORDS: VocabularyWord[] = [
  {
    id: '1',
    word: 'serendipity',
    translation: 'casualidad afortunada',
    phonetic: '/ˌserənˈdɪpɪti/',
    audioUrl: 'https://example.com/audio/serendipity.mp3',
    imageUrl: 'https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=400',
    example: 'Finding that book was pure serendipity.',
    exampleTranslation: 'Encontrar ese libro fue pura casualidad.',
    level: 'C1',
    language: 'en',
    dateAdded: new Date('2024-01-15'),
    isLearned: false,
    reviewCount: 0,
  },
  {
    id: '2',
    word: 'ephemeral',
    translation: 'efímero',
    phonetic: '/ɪˈfemərəl/',
    example: 'The beauty of cherry blossoms is ephemeral.',
    exampleTranslation: 'La belleza de las flores de cerezo es efímera.',
    level: 'B2',
    language: 'en',
    dateAdded: new Date('2024-01-14'),
    isLearned: true,
    reviewCount: 3,
    lastReviewed: new Date('2024-01-16'),
  },
  {
    id: '3',
    word: 'ubiquitous',
    translation: 'omnipresente',
    phonetic: '/juːˈbɪkwɪtəs/',
    example: 'Smartphones have become ubiquitous in modern society.',
    exampleTranslation: 'Los smartphones se han vuelto omnipresentes en la sociedad moderna.',
    level: 'C1',
    language: 'en',
    dateAdded: new Date('2024-01-13'),
    isLearned: false,
    reviewCount: 1,
  },
  {
    id: '4',
    word: 'ameliorate',
    translation: 'mejorar',
    phonetic: '/əˈmiːliəreɪt/',
    example: 'The new policies helped ameliorate the situation.',
    exampleTranslation: 'Las nuevas políticas ayudaron a mejorar la situación.',
    level: 'C2',
    language: 'en',
    dateAdded: new Date('2024-01-12'),
    isLearned: false,
    reviewCount: 0,
  },
  {
    id: '5',
    word: 'pragmatic',
    translation: 'pragmático',
    phonetic: '/præɡˈmætɪk/',
    example: 'We need a pragmatic approach to this problem.',
    exampleTranslation: 'Necesitamos un enfoque pragmático para este problema.',
    level: 'B2',
    language: 'en',
    dateAdded: new Date('2024-01-11'),
    isLearned: true,
    reviewCount: 2,
    lastReviewed: new Date('2024-01-15'),
  },
];

export const MOCK_SESSIONS: LearningSession[] = [
  {
    id: '1',
    date: new Date('2024-01-16'),
    wordsLearned: 12,
    timeSpent: 18,
    accuracy: 85,
  },
  {
    id: '2',
    date: new Date('2024-01-15'),
    wordsLearned: 15,
    timeSpent: 22,
    accuracy: 92,
  },
  {
    id: '3',
    date: new Date('2024-01-14'),
    wordsLearned: 8,
    timeSpent: 15,
    accuracy: 78,
  },
  {
    id: '4',
    date: new Date('2024-01-13'),
    wordsLearned: 20,
    timeSpent: 25,
    accuracy: 88,
  },
  {
    id: '5',
    date: new Date('2024-01-12'),
    wordsLearned: 10,
    timeSpent: 16,
    accuracy: 90,
  },
];